
- name: update /etc/hosts file
  shell: echo "127.0.0.1 {{ host_name }}" >> /etc/hosts

- name: set host name
  hostname:
    name: "{{ host_name }}"
    
- name: Allow connections on multiple tcp ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
      - "22"
      - "8090"
    jump: ACCEPT

- name: Allow connections on multiple udp ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_ports:
      - "53"
    jump: ACCEPT
    
- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow loopback
  ansible.builtin.iptables:
    chain: INPUT
    source: 127.0.0.1
    jump: ACCEPT

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Set the policy for the FORWARD chain to DROP
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP